### PR TITLE
Write a better Dockerfile

### PR DESCRIPTION
**Pull request by JayH5**
- Standard Debian Jessie base image
- OpenJDK 8
- Grails 2.5.2

The current Dockerfile is based off an image that is based off an Ubuntu 14.04.1 image that claims to be "unopinionated" but really just has an opinion that differs to ours. It installs a whole bunch of stuff including an init system that we don't want to use.

1.261 GB -> 623.3 MB

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@JayH5 looks sensible to me, but I'd rather @hodgestar provide the +1 because I can't test this right right to validate

**Comment by hodgestar** [comment]
Looks good. The Travis builds run against openjdk7, so if our docker file uses openjdk8, perhaps we should adjust the Travis builds to do the same?

**Comment by JayH5** [comment]
@hodgestar I had had the thought but according to the Travis docs there is openjdk7 and oraclejdk8 but no openjdk8... I guess we could do oraclejdk8? I'm keen to use JDK 8 whenever possible as Java 7 is not receiving any more public updates from Oracle since April (although there still seem to have been a few new OpenJDK releases).

**Comment by hodgestar** [comment]
Silly Travis. I second the vote for switching Travis to oraclejdk8.

**Comment by JayH5** [comment]
@hodgestar: Done :)

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
