### PR TITLE
When a schedule fires, the message parameters should be posted in the HTTP body, not as query parameters.

### PR DESCRIPTION
**Pull request by hodgestar**
screenshot from 2015-05-21 17 53 26

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review.

**Comment by hodgestar** [comment]
@LyndsayLawrence Any chance you're up for reviewing this change? :)

**Comment by hodgestar** [comment]
@smn Any chance you could review this?

**Comment by smn** [comment]
:+1: good catch.

**Comment by hodgestar** [comment]
@smn Tx. It was actually caught by QA (yay for Sheetal and junior-SRE).

**Pull request merged**
