### PR TITLE
removed config from jobs

### PR DESCRIPTION
**Pull request by LyndsayLawrence**

### CODE REVIEW

**Comment by hodgestar** [comment]
Won't this prevent us from configuring a shorter time interval for QA?

**Comment by hodgestar** [comment]
http://stackoverflow.com/a/7420854 seems to have an solution.

**Comment by LyndsayLawrence** [comment]
ConfigHolder is ver old grails. I have a solution though

**Comment by LyndsayLawrence** [comment]
Please review

**Comment by smn** [comment]
:+1: thanks.

**Comment by smn** [comment]
hrm this broke something because: 

```
2015-04-17 14:28:42,944 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: CronExpression '60' is invalid.
java.lang.RuntimeException: CronExpression '60' is invalid.
```

**Pull request merged**
